use_temp_auth: "false"
proxy_obfuscated_prefix: ""
account_db_max_writes_per_sec: 100
container_db_max_writes_per_sec: 100
proxy_port: 8080

tracing_enabled: false
tracing_agent_host_port: 127.0.0.1:6831
tracing_sampler_type: ratelimiting
tracing_sampler_param: 2.0
tracing_reporter_log_spans: false
tracing_enable_httptrace: true
