---
- hosts: hummingbird
  become: yes
  roles:
    - { role: hummingbird-common, tags: ['common'] }
    - { role: hummingbird-filebeat, tags: ['common'] }
    - { role: hummingbird-storage, tags: ['storage'] }
    - { role: hummingbird-ring, tags: ['ring'] }
    - { role: hummingbird-proxy-server, tags: ['proxy-server'] }
    - { role: hummingbird-account-server, tags: ['account-server'] }
    - { role: hummingbird-container-server, tags: ['container-server'] }
    - { role: hummingbird-object-server, tags: ['object-server'] }
- hosts: hummingbird-andrewd
  become: yes
  roles:
    - { role: hummingbird-common, binary_only: yes, tags: ['common'] }
    - { role: hummingbird-andrewd, tags: ['andrewd'] }
