---
- hosts: "{{ groups['hummingbird-admin'][0] }}"
  become: yes
  roles:
    - role: hummingbird-common
      binary_only: yes
  pre_tasks:
    - name: Debug
      debug:
        var: groups
    - name: Load hummingbird vars
      include_vars:
        file: group_vars/hummingbird/hummingbird
  tasks:
    - name: Make sure jmespath is installed
      apt:
        name: python-jmespath
        state: present
    - name: Check if object.builder exists
      stat: path=/etc/hummingbird/object.builder
      register: object_builder
    - name: Check if container.builder exists
      stat: path=/etc/hummingbird/container.builder
      register: container_builder
    - name: Check if account.builder exists
      stat: path=/etc/hummingbird/account.builder
      register: account_builder
    - name: Create object ring
      command: hummingbird ring /etc/hummingbird/object.builder create {{object_ring_part_power | default(20)}} {{object_ring_replicas | default(6)}} {{object_ring_min_part_hours | default(168)}}
      when: not object_builder.stat.exists
    - name: Set object ring perms
      file:
        path: /etc/hummingbird/object.builder
        owner: hummingbird
        group: hummingbird
      when: not object_builder.stat.exists
    - name: Create container ring
      command: hummingbird ring /etc/hummingbird/container.builder create {{container_ring_part_power | default(20)}} {{container_ring_replicas | default(3)}} {{container_ring_min_part_hours | default(168)}}
      when: not container_builder.stat.exists
    - name: Set container ring perms
      file:
        path: /etc/hummingbird/container.builder
        owner: hummingbird
        group: hummingbird
      when: not container_builder.stat.exists
    - name: Create account ring
      command: hummingbird ring /etc/hummingbird/account.builder create {{account_ring_part_power | default(20)}} {{account_ring_replicas | default(3)}} {{account_ring_min_part_hours | default(168)}}
      when: not account_builder.stat.exists
    - name: Set account ring perms
      file:
        path: /etc/hummingbird/account.builder
        owner: hummingbird
        group: hummingbird
      when: not account_builder.stat.exists

- hosts: hummingbird
  serial: 1
  become: yes
  tasks:
    - name: Create cust fact dir
      file:
        path: /etc/ansible/facts.d
        state: directory
    - name: Push devmap fact file
      copy:
        src: scripts/devmap.py
        dest: /etc/ansible/facts.d/devmap.fact
        mode: 0755
    - name: Re-run setup to pull facts
      setup: ~
    - name: Get devices that are already in the object ring for this node
      command: hummingbird ring -json /etc/hummingbird/object.builder search -ip {{service_ip}}
      register: result
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True
    - set_fact: object_ring_devices="{{ result.stdout | from_json |  json_query('[*].Device')}}"
    - name: Add devices to object ring
      command: hummingbird ring /etc/hummingbird/object.builder add r1z{{ groups.hummingbird.index(inventory_hostname)+1 }}-{{ service_ip }}:{{ object_port | default(6000) }}R{{ replication_ip | default(service_ip) }}:{{ object_replicator_port | default(6500) }}/{{ item }}1 {{ hostvars[inventory_hostname]["ansible_devices"][ansible_local.devmap[item]]["size"] | human_to_bytes/1024/1024/1024 | round }}
      with_items: "{{ object_devs | default(storage_devs) }}"
      when: item not in object_ring_devices and state != "remove" and ansible_local.devmap[item] is defined
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True
    - name: Remove devices from object ring if the node is removed
      command: hummingbird ring /etc/hummingbird/object.builder remove -ip {{service_ip}} -yes
      when: state == "remove"
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True
    - name: Get devices that are already in the container ring for this node
      command: hummingbird ring -json /etc/hummingbird/container.builder search -ip {{service_ip}}
      register: result
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True
    - set_fact: container_ring_devices="{{ result.stdout | from_json |  json_query('[*].Device')}}"
    - name: Add devices to container ring
      command: hummingbird ring /etc/hummingbird/container.builder add r1z{{ groups.hummingbird.index(inventory_hostname)+1 }}-{{ service_ip }}:{{ container_port | default(6001) }}R{{ replication_ip | default(service_ip) }}:{{ container_replicator_port | default(6501) }}/{{ item }}1 {{ hostvars[inventory_hostname]["ansible_devices"][ansible_local.devmap[item]]["size"] | human_to_bytes/1024/1024/1024 | round }}
      with_items: "{{ container_devs | default(storage_devs) }}"
      when: item not in container_ring_devices and state != "remove" and ansible_local.devmap[item] is defined
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True
    - name: Remove devices from container ring if the node is removed
      command: hummingbird ring /etc/hummingbird/container.builder remove -ip {{service_ip}} -yes
      when: state == "remove"
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True
    - name: Get devices that are already in the account ring for this node
      command: hummingbird ring -json /etc/hummingbird/account.builder search -ip {{service_ip}}
      register: result
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True
    - set_fact: account_ring_devices="{{ result.stdout | from_json |  json_query('[*].Device')}}"
    - name: Add devices to account ring
      command: hummingbird ring /etc/hummingbird/account.builder add r1z{{ groups.hummingbird.index(inventory_hostname)+1 }}-{{ service_ip }}:{{ account_port | default(6002) }}R{{ replication_ip | default(service_ip) }}:{{ account_replicator_port | default(6502) }}/{{ item }}1 {{ hostvars[inventory_hostname]["ansible_devices"][ansible_local.devmap[item]]["size"] | human_to_bytes/1024/1024/1024 | round}}
      with_items: "{{ account_devs | default(storage_devs) }}"
      when: item not in account_ring_devices and state != "remove" and ansible_local.devmap[item] is defined
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True
    - name: Remove devices from account ring if the node is removed
      command: hummingbird ring /etc/hummingbird/account.builder remove -ip {{service_ip}} -yes
      when: state == "remove"
      delegate_to: "{{ groups['hummingbird-admin'][0] }}"
      delegate_facts: True

- hosts: "{{ groups['hummingbird-admin'][0] }}"
  become: yes
  tasks:
    - name: Rebalance object ring
      command: hummingbird ring /etc/hummingbird/object.builder rebalance
    - name: Set object ring perms
      file:
        path: /etc/hummingbird/object.ring.gz
        owner: hummingbird
        group: hummingbird
    - name: Rebalance container ring
      command: hummingbird ring /etc/hummingbird/container.builder rebalance
    - name: Set container ring perms
      file:
        path: /etc/hummingbird/container.ring.gz
        owner: hummingbird
        group: hummingbird
    - name: Rebalance account ring
      command: hummingbird ring /etc/hummingbird/account.builder rebalance
    - name: Set account ring perms
      file:
        path: /etc/hummingbird/account.ring.gz
        owner: hummingbird
        group: hummingbird
    - name: Set backup perms
      file:
        path: /etc/hummingbird/backups
        state: directory
        owner: hummingbird
        group: hummingbird
        recurse: yes
