---
- name: Copy account server config
  template:
    src: etc/account-server.j2
    dest: /etc/hummingbird/account-server.conf
    mode: 0644
    owner: hummingbird
    group: hummingbird
- name: Copy account server systemd files
  copy:
    src: systemd/hummingbird-account.service
    dest: /lib/systemd/system/hummingbird-account.service
    mode: 0644
- name: Copy account replicator systemd files
  copy:
    src: systemd/hummingbird-account-replicator.service
    dest: /lib/systemd/system/hummingbird-account-replicator.service
    mode: 0644
- name: Start account service
  systemd:
    name: hummingbird-account
    enabled: yes
    state: reloaded
    daemon_reload: yes
- name: Start account replicator service
  systemd: 
    name: hummingbird-account-replicator
    enabled: yes
    state: reloaded
    daemon_reload: yes
